name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "zee@infinity.ai"
          git config --global user.name "Zeeshan Agent"
          git push --force https://zeesh902:$HF_TOKEN@huggingface.co/spaces/zeesh902/Infinte_ChatAI HEAD:main
